"""Initial migration

Revision ID: 5bc3d1e6b181
Revises: 
Create Date: 2026-04-01 21:18:29.409208

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = '5bc3d1e6b181'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('user_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('role', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('action', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('resource', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('resource_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('method', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('params', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('ip_address', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('user_agent', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('status_code', sa.Integer(), nullable=True),
    sa.Column('response_msg', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_logs_action'), ['action'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_user_id'), ['user_id'], unique=False)

    op.create_table('checkin_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=True),
    sa.Column('student_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('student_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('class_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('checkin_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('checkin_time', sa.DateTime(), nullable=False),
    sa.Column('checkin_lat', sa.Float(), nullable=True),
    sa.Column('checkin_lng', sa.Float(), nullable=True),
    sa.Column('checkin_distance', sa.Float(), nullable=True),
    sa.Column('device_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('device_info', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('checkin_records', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_checkin_records_class_name'), ['class_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_checkin_records_device_id'), ['device_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_checkin_records_session_id'), ['session_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_checkin_records_student_id'), ['student_id'], unique=False)

    op.create_table('class_session',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_code', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('course_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('class_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('teacher_id', sa.Integer(), nullable=True),
    sa.Column('teacher_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('start_time', sa.DateTime(), nullable=True),
    sa.Column('end_time', sa.DateTime(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('location_lat', sa.Float(), nullable=True),
    sa.Column('location_lng', sa.Float(), nullable=True),
    sa.Column('location_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('checkin_radius', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('class_session', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_class_session_class_name'), ['class_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_class_session_session_code'), ['session_code'], unique=False)
        batch_op.create_index(batch_op.f('ix_class_session_teacher_id'), ['teacher_id'], unique=False)

    op.create_table('course_schedules',
    sa.Column('course_name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('class_name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('teacher_id', sa.Integer(), nullable=True),
    sa.Column('teacher_name', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('day_of_week', sa.Integer(), nullable=False),
    sa.Column('start_time', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('end_time', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('classroom', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('week_start', sa.Integer(), nullable=False),
    sa.Column('week_end', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('updated_at', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('score_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('old_score', sa.Float(), nullable=True),
    sa.Column('new_score', sa.Float(), nullable=True),
    sa.Column('delta', sa.Float(), nullable=True),
    sa.Column('reason', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('operator', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('score_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_score_logs_student_id'), ['student_id'], unique=False)

    op.create_table('security_alerts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('alert_type', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('severity', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('related_user_id', sa.Integer(), nullable=True),
    sa.Column('related_ip', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('is_resolved', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('security_alerts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_security_alerts_alert_type'), ['alert_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_security_alerts_is_resolved'), ['is_resolved'], unique=False)

    op.create_table('students',
    sa.Column('student_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('class_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('is_account_enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.Column('password_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('student_id')
    )
    op.create_table('users',
    sa.Column('username', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('role', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('assigned_classes', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('is_account_enabled', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('password_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('login_fail_count', sa.Integer(), nullable=False),
    sa.Column('locked_until', sa.DateTime(), nullable=True),
    sa.Column('last_login_ip', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.drop_table('students')
    with op.batch_alter_table('security_alerts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_security_alerts_is_resolved'))
        batch_op.drop_index(batch_op.f('ix_security_alerts_alert_type'))

    op.drop_table('security_alerts')
    with op.batch_alter_table('score_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_score_logs_student_id'))

    op.drop_table('score_logs')
    op.drop_table('course_schedules')
    with op.batch_alter_table('class_session', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_class_session_teacher_id'))
        batch_op.drop_index(batch_op.f('ix_class_session_session_code'))
        batch_op.drop_index(batch_op.f('ix_class_session_class_name'))

    op.drop_table('class_session')
    with op.batch_alter_table('checkin_records', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_checkin_records_student_id'))
        batch_op.drop_index(batch_op.f('ix_checkin_records_session_id'))
        batch_op.drop_index(batch_op.f('ix_checkin_records_device_id'))
        batch_op.drop_index(batch_op.f('ix_checkin_records_class_name'))

    op.drop_table('checkin_records')
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_logs_user_id'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_created_at'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_action'))

    op.drop_table('audit_logs')
    # ### end Alembic commands ###
