"""add missing query performance indexes

Revision ID: e20c12c98147
Revises: 04d1e8d50a37
Create Date: 2026-04-12 19:40:30.707599

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e20c12c98147'
down_revision: Union[str, Sequence[str], None] = '04d1e8d50a37'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('checkin_records', schema=None) as batch_op:
        batch_op.create_index('idx_checkin_records_checkin_time', [sa.literal_column('checkin_time DESC')], unique=False)

    with op.batch_alter_table('score_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_score_logs_student_id'))
        batch_op.create_index('idx_score_logs_student_created_at', ['student_id', sa.literal_column('created_at DESC')], unique=False)

    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.create_index('idx_students_class_name', ['class_name'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.drop_index('idx_students_class_name')

    with op.batch_alter_table('score_logs', schema=None) as batch_op:
        batch_op.drop_index('idx_score_logs_student_created_at')
        batch_op.create_index(batch_op.f('ix_score_logs_student_id'), ['student_id'], unique=False)

    with op.batch_alter_table('checkin_records', schema=None) as batch_op:
        batch_op.drop_index('idx_checkin_records_checkin_time')

    # ### end Alembic commands ###
